[package]
name = "joycon-rs"
version = "0.1.0"
authors = ["Kaisei Yokoyama <yokoyama.kaisei.sm@alumni.tsukuba.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#hidapi = "1.2.1"
hidapi = { git = "https://github.com/KaiseiYokoyama/hidapi-rs" }